[tool.black]
line-length = 79
target-version = ["py312"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
  | load_test_data
)/
'''

[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
known_first_party = "service_auth"
known_django = "django"
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"
skip = ["venv", "migrations", ".git", "load_test_data"]

[tool.mypy]
python_version = 3.13
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true
strict_optional = true
exclude = '(/venv/|/migrations/|/build/|/dist/|\.git/|/load_test_data/|)'
disable_error_code = [
    "prop-decorator",
]

[tool.flake8]
max-line-length = 79
extend-ignore = "E203,W503"
exclude = ".git,__pycache__,venv,migrations,load_test_data"
