# Generated by Django 5.2.5 on 2025-09-03 09:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserByGroupAssociation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания сущности')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Время обновления сущности')),
                ('deleted_at', models.DateTimeField(default=None, help_text='Время удаления сущности (мягкое удаление)', null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_by_group', to='api_auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_by_group', to='api_auth.user')),
            ],
            options={
                'db_table': 'users"."user_by_group_association',
            },
        ),
        migrations.DeleteModel(
            name='UserPermissionByGroupAssociation',
        ),
        migrations.AddConstraint(
            model_name='userbygroupassociation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'group'), name='unique_user_group_permission', violation_error_message='Пользователь уже добавлен в указанную группу'),
        ),
    ]
